# Generated by Django 5.2.6 on 2025-11-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='friends',
            new_name='companions',
        ),
    ]
