# Generated by Django 5.2.6 on 2025-12-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_rename_friends_trip_companions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='owner',
            new_name='user',
        ),
    ]
