# Generated by Django 5.2.6 on 2026-01-15 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_rename_owner_trip_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(help_text='Matching score (0-100)')),
                ('common_interests', models.JSONField(default=list)),
                ('distance_km', models.FloatField(blank=True, help_text='Distance between destinations in km', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='companions',
            new_name='current_companions',
        ),
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text='List of interests/activities for the trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='max_companions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('friends_only', 'Friends Only'), ('private', 'Private')], default='friends_only', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user'], name='travel_trip_user_id_1e3a10_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['start_date', 'end_date'], name='travel_trip_start_d_b876fa_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['destination'], name='travel_trip_destina_c59fa0_idx'),
        ),
        migrations.AddField(
            model_name='tripmatch',
            name='matched_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reverse_matches', to='travel.trip'),
        ),
        migrations.AddField(
            model_name='tripmatch',
            name='matched_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripmatch',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='travel.trip'),
        ),
        migrations.AddIndex(
            model_name='tripmatch',
            index=models.Index(fields=['trip', 'status'], name='travel_trip_trip_id_3ba3a3_idx'),
        ),
        migrations.AddIndex(
            model_name='tripmatch',
            index=models.Index(fields=['matched_user', 'status'], name='travel_trip_matched_dc9398_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tripmatch',
            unique_together={('trip', 'matched_user')},
        ),
    ]
