# Generated by Django 5.2.6 on 2026-01-17 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_tripmatch_rename_companions_trip_current_companions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(blank=True, help_text='Location accuracy in meters', null=True)),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in meters', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in meters per second', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Heading/bearing in degrees (0-360)', null=True)),
                ('is_background', models.BooleanField(default=False, help_text='Whether location was recorded in background')),
                ('battery_level', models.IntegerField(blank=True, help_text='Device battery level (0-100)', null=True)),
                ('recorded_at', models.DateTimeField(help_text='When the location was actually recorded by device')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(blank=True, help_text='Associated trip if location was recorded during active trip', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_points', to='travel.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location History',
                'verbose_name_plural': 'Location Histories',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['user', '-recorded_at'], name='travel_loca_user_id_5e0a65_idx'), models.Index(fields=['trip', '-recorded_at'], name='travel_loca_trip_id_922429_idx'), models.Index(fields=['latitude', 'longitude'], name='travel_loca_latitud_a2b7dc_idx'), models.Index(fields=['recorded_at'], name='travel_loca_recorde_40099b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TripSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggestion_type', models.CharField(choices=[('activity', 'Activity'), ('food', 'Food'), ('safety', 'Safety'), ('cultural', 'Cultural'), ('hidden_gem', 'Hidden Gem'), ('timing', 'Timing'), ('warning', 'Warning')], max_length=20)),
                ('content', models.TextField(help_text='The suggestion text generated by AI')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_name', models.CharField(blank=True, help_text='Name of place if suggestion is location-specific', max_length=255)),
                ('related_place_id', models.UUIDField(blank=True, help_text='ID of related place from insights app', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_acted_upon', models.BooleanField(default=False, help_text='Whether user acted on this suggestion')),
                ('user_rating', models.IntegerField(blank=True, help_text='User rating 1-5 stars', null=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='travel.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip Suggestion',
                'verbose_name_plural': 'Trip Suggestions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'trip', '-created_at'], name='travel_trip_user_id_bbd5bc_idx'), models.Index(fields=['trip', 'is_read'], name='travel_trip_trip_id_7710c0_idx'), models.Index(fields=['suggestion_type'], name='travel_trip_suggest_633d63_idx'), models.Index(fields=['latitude', 'longitude'], name='travel_trip_latitud_64cc4c_idx')],
            },
        ),
    ]
