# Generated by Django 5.2.6 on 2026-01-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_locationhistory_tripsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether the trip has been started and matching is active'),
        ),
        migrations.AddField(
            model_name='tripmatch',
            name='current_distance_km',
            field=models.FloatField(blank=True, help_text='Current real-time distance between users in km', null=True),
        ),
        migrations.AddField(
            model_name='tripmatch',
            name='is_proximity_expired',
            field=models.BooleanField(default=False, help_text='Auto-expired due to distance threshold exceeded'),
        ),
        migrations.AddField(
            model_name='tripmatch',
            name='last_distance_update',
            field=models.DateTimeField(blank=True, help_text='When current_distance_km was last updated', null=True),
        ),
    ]
