# Generated by Django 5.2.6 on 2026-01-19 19:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_trip_is_active_tripmatch_current_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripsuggestion',
            name='hotspot_friend_names',
            field=models.JSONField(blank=True, default=list, help_text='List of friend names if any friends are in the hotspot'),
        ),
        migrations.AddField(
            model_name='tripsuggestion',
            name='hotspot_user_count',
            field=models.IntegerField(blank=True, help_text='Number of users at this hotspot location', null=True),
        ),
        migrations.AlterField(
            model_name='tripsuggestion',
            name='suggestion_type',
            field=models.CharField(choices=[('activity', 'Activity'), ('food', 'Food'), ('safety', 'Safety'), ('cultural', 'Cultural'), ('hidden_gem', 'Hidden Gem'), ('timing', 'Timing'), ('warning', 'Warning'), ('activity_hotspot', 'Activity Hotspot')], max_length=20),
        ),
        migrations.CreateModel(
            name='ActivityHotspot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('place_name', models.CharField(blank=True, help_text='Name of the place (matched from insights DB)', max_length=255)),
                ('related_place_id', models.UUIDField(blank=True, help_text='ID of related place from insights app', null=True)),
                ('user_count', models.IntegerField(default=0)),
                ('active_users', models.JSONField(default=list, help_text='List of user IDs currently at this location')),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='When this hotspot expires if no activity')),
            ],
            options={
                'verbose_name': 'Activity Hotspot',
                'verbose_name_plural': 'Activity Hotspots',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='travel_acti_latitud_8e129a_idx'), models.Index(fields=['-last_activity'], name='travel_acti_last_ac_b651b1_idx'), models.Index(fields=['expires_at'], name='travel_acti_expires_a6a2c9_idx'), models.Index(fields=['user_count'], name='travel_acti_user_co_676723_idx')],
            },
        ),
    ]
