# Generated by Django 5.2.6 on 2025-12-07 13:39

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city'], name='insights_pl_city_91560f_idx'), models.Index(fields=['state'], name='insights_pl_state_c14bbc_idx'), models.Index(fields=['country'], name='insights_pl_country_90c429_idx'), models.Index(fields=['latitude', 'longitude'], name='insights_pl_latitud_675bda_idx')],
                'unique_together': {('city', 'state', 'country')},
            },
        ),
        migrations.CreateModel(
            name='PlaceInsights',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('history', models.TextField()),
                ('cultural_notes', models.TextField()),
                ('famous_for', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('things_to_do', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('food_specialties', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('quotes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None)),
                ('hero_image_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('neighbourhood_patterns', models.JSONField(blank=True, default=list, null=True)),
                ('tourist_traps', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None)),
                ('time_based_actions', models.JSONField(default=dict)),
                ('hidden_gems', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None)),
                ('is_stale', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('last_requested', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='insights.place')),
            ],
        ),
        migrations.CreateModel(
            name='TouristTrap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trap_areas', to='insights.place')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalInsights',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('recommended_activities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('cautions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_insights', to='insights.place')),
            ],
            options={
                'unique_together': {('place', 'season')},
            },
        ),
    ]
