# Generated by Django 5.2.6 on 2026-01-02 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=200)),
                ('day_time', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Day Activities',
            },
        ),
        migrations.CreateModel(
            name='FamousActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamousPlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('quote', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodSpecialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Food Specialties',
            },
        ),
        migrations.CreateModel(
            name='HiddenGem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MostFamousPlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('quote', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThingToDo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Things To Do',
            },
        ),
        migrations.AlterModelOptions(
            name='placeinsights',
            options={'verbose_name': 'Place Insight', 'verbose_name_plural': 'Place Insights'},
        ),
        migrations.RenameField(
            model_name='placeinsights',
            old_name='cultural_notes',
            new_name='main_quote',
        ),
        migrations.RenameField(
            model_name='placeinsights',
            old_name='history',
            new_name='sub_quote',
        ),
        migrations.RemoveField(
            model_name='placeinsights',
            name='famous_for',
        ),
        migrations.RemoveField(
            model_name='placeinsights',
            name='food_specialties',
        ),
        migrations.RemoveField(
            model_name='placeinsights',
            name='hero_image_keywords',
        ),
        migrations.RemoveField(
            model_name='placeinsights',
            name='hidden_gems',
        ),
        migrations.RemoveField(
            model_name='placeinsights',
            name='neighbourhood_patterns',
        ),
        migrations.RemoveField(
            model_name='placeinsights',
            name='quotes',
        ),
        migrations.RemoveField(
            model_name='placeinsights',
            name='things_to_do',
        ),
        migrations.RemoveField(
            model_name='placeinsights',
            name='time_based_actions',
        ),
        migrations.RemoveField(
            model_name='placeinsights',
            name='tourist_traps',
        ),
        migrations.AlterField(
            model_name='placeinsights',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='insights.place'),
        ),
        migrations.AddIndex(
            model_name='placeinsights',
            index=models.Index(fields=['expires_at'], name='insights_pl_expires_8e1288_idx'),
        ),
        migrations.AddIndex(
            model_name='placeinsights',
            index=models.Index(fields=['is_stale'], name='insights_pl_is_stal_8402aa_idx'),
        ),
        migrations.AddField(
            model_name='dayactivity',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_activities', to='insights.place'),
        ),
        migrations.AddField(
            model_name='famousactivity',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notable_activities', to='insights.place'),
        ),
        migrations.AddField(
            model_name='famousplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notable_places', to='insights.place'),
        ),
        migrations.AddField(
            model_name='foodspecialty',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_specialties', to='insights.place'),
        ),
        migrations.AddField(
            model_name='hiddengem',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_gems', to='insights.place'),
        ),
        migrations.AddField(
            model_name='mostfamousplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='famous_places', to='insights.place'),
        ),
        migrations.AddField(
            model_name='thingtodo',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='things_to_do', to='insights.place'),
        ),
    ]
