# Generated by Django 5.2.6 on 2026-01-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_dayactivity_famousactivity_famousplace_foodspecialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
