# Generated by Django 5.2.6 on 2026-01-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famousplace',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mostfamousplace',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
