# Generated by Django 5.2.6 on 2026-01-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0004_alter_famousplace_image_alter_mostfamousplace_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='theme_color',
            field=models.CharField(blank=True, default='', help_text="Hex color code representing city's theme (e.g., #3B82F6 for blue)", max_length=7),
        ),
        migrations.AddField(
            model_name='place',
            name='visual_tags',
            field=models.CharField(blank=True, default='', help_text='Visual keywords for image search: sunset, mountains, modern, historic, etc.', max_length=200),
        ),
    ]
