# Generated by Django 5.2.6 on 2025-10-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Info',
        ),
    ]
