# Generated by Django 5.2.6 on 2025-12-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_sociallink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='trips_count',
            new_name='adventures',
        ),
    ]
