# Generated by Django 5.2.6 on 2026-01-02 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0010_rename_trips_count_social_adventures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='social',
            name='favorites',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['latitude', 'longitude'], name='user_profil_latitud_17be64_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['show_location'], name='user_profil_show_lo_c783c6_idx'),
        ),
        migrations.AddIndex(
            model_name='sociallink',
            index=models.Index(fields=['user', 'platform'], name='user_social_user_id_0c4bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_user_email_5f6a77_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'email_verified'], name='user_user_is_acti_57799c_idx'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'name'], name='user_favori_user_id_df6a09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'name', 'location')},
        ),
    ]
