# Generated by Django 5.2.6 on 2026-01-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0011_favorite_alter_profile_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='External profile image URL (e.g., from Google, Facebook)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(default='email', help_text='Authentication provider: email, google, facebook, apple, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, help_text='Firebase User ID for OAuth users', max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Uploaded profile image', null=True, upload_to='profile_images/'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['firebase_uid'], name='user_user_firebas_0cf862_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['auth_provider'], name='user_user_auth_pr_b1b98d_idx'),
        ),
    ]
