# Generated by Django 5.2.6 on 2026-01-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_profile_profile_image_url_user_auth_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
