# Generated by Django 5.2.6 on 2026-01-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_profile_last_location_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='Profile image URL (uploaded or from OAuth provider like Google)', max_length=500, null=True),
        ),
    ]
